categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '📄 Documentation'
    labels:
      - 'docs'
  - title: '🧰 Maintenance'
    label: 'chore'
autolabeler:
  - label: 'docs'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'chore'
    files:
      - '*.sbt'
    branch:
      - '/chore\/.+/'
      - '/update\/.+/'
    title:
      - '/updated? .+ to \d+\.\d[\w\.-]*/i'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
template: |
  ## What’s Changed

  $CHANGES