language: scala
scala:
  - 2.12.8
before_install:
  - git fetch --tags
before_script:
  - sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/Ammonite/releases/download/1.6.9/2.12-1.6.9) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm'
jobs:
  include:
  - stage: pull request testing
    if: type = pull_request
    script: sbt clean coverage tests/test coverageReport codacyCoverage

  - name: formatting check
    if: type = pull_request
    script: sbt scalafmtCheckAll scalafmtSbtCheck

  - stage: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
    script: sbt ci-release
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
  - "$HOME/.coursier/cache"
