language: scala
scala:
  - 2.12.8
before_install:
  - git fetch --tags
before_script:
  - sudo sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/Ammonite/releases/download/1.6.9/2.12-1.6.9) > /usr/local/bin/amm && chmod +x /usr/local/bin/amm'
jobs:
  include:
  - stage: pull request testing
    if: type = pull_request
    script: sbt clean coverage tests/test coverageReport codacyCoverage

  - name: formatting check
    if: type = pull_request
    script: sbt scalafmtCheckAll scalafmtSbtCheck

  - stage: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
    script: sbt ci-release
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
  - "$HOME/.coursier/cache"
env:
  global:
    secure: YI1WM/rFL1EilUDMsFKzbQIdla8aIy1hpIx7GOhvIRJGKvc3A8lGdsNLLcWo4qbXjiNVSzwYHO9tWQbXwPtMVnM8rdMSzDfNYWX93SvHNEcXA3iYKlkCACfFNckwFBw9HS/HQqif57SoaAIVaYXciG3xezecAxFtM1PRCtfqKu93ywRmSpajrBDfDRF8NahXHtbs1EwPl15/RtPpIWbsFL68OtD6HbdlNqSMm2rp7roYhXBLbRIPd/ABQCZfjBvK4kiuEpQp15Fq3mgU3kohiFiQjuGarp00gVvdeKbkWFwwhv/wmHJ4ewnUvKtl1j3AHtVzNmwhdi7hD1hm1CoCLJErAS/y8iNubXYCF27s/eEa4HIOwUEbVEukP2uF/aaz04Zw3OmqcVEAYDMuPNvywCDg+JrLnglFB5YJ/0KykR+SOSdKjcf9k4tDX7BQd7he7HiyT2/Ty4OPktynhYdxnwGcwOk0D+/aMc1kobEumlr0Cxgn0MQ8n5iy5YA6FJIRdyjdhhUHQaKfEUI5Th7nek0H3aRHR4fAEXlEvBVuAvshT49iVnQlINPrTPg2iUjiCEh+MTllY1ce2txvhq32XuAlUosAjK93SQvdjAhbpc78KFqeQl6odBeZaTn3Lhje7N1+GnkkJ+zN0yoEn67dZcy4rT72yACjiOVFSDij5BE=
