language: scala
scala:
  - 2.12.11
jdk:
  - openjdk8
before_install:
  - git fetch --tags
before_script:
  - shopt -s expand_aliases
  - alias sbt="sbt -Dsbt.color=always"
  - export PATH="$PATH:$(pwd)/bin:$HOME/.local/share/coursier/bin"
jobs:
  include:
#    - stage: testing
#      name: running unit tests
#      if: (type = pull_request) OR (branch = master AND type = push)
#      script:
#        - if [[ -n "$COVERALLS_REPO_TOKEN" ]]; then
#            sbt clean "set core/coverageEnabled:=true" "set cli/coverageEnabled:=true" test coverageReport \
#              && sbt coverageAggregate coveralls;
#          else
#            sbt clean "set core/coverageEnabled:=true" "set cli/coverageEnabled:=true" test coverageReport;
#          fi
#
#    - name: formatting check
#      if: type = pull_request
#      script:
#        - sbt scalafmtCheckAll scalafmtSbtCheck
#
#    - name: mutation testing core 1/2
#      if: type = pull_request
#      script:
#        - ./travis/setup.sh && amm travis/runCurrentVersion.sc "travis/core.blinky.conf" --multiRun 1/2
#
#    - name: mutation testing core 2/2
#      if: type = pull_request
#      script:
#        - ./travis/setup.sh && amm travis/runCurrentVersion.sc "travis/core.blinky.conf" --multiRun 2/2
#
#    - name: mutation testing cli 1/2
#      if: type = pull_request
#      script:
#        - ./travis/setup.sh && amm travis/runCurrentVersion.sc "travis/cli.blinky.conf" --multiRun 1/2
#
#    - name: mutation testing cli 2/2
#      if: type = pull_request
#      script:
#        - ./travis/setup.sh && amm travis/runCurrentVersion.sc "travis/cli.blinky.conf" --multiRun 2/2
#
#    - name: mutation testing examples
#      if: type = pull_request
#      script:
#        - ./travis/setup.sh && amm travis/runExamples.sc
#
#    - stage: release
#      name: release
#      if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
#      script:
#        - sbt ci-release docs/docusaurusPublishGhpages
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.cache/coursier"
