name: CI

on:
  push:
    branches:
      - master
  #pull_request:
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - name: Tests Coverage
        run: |
          sbt clean "set core/coverageEnabled:=true" "set cli/coverageEnabled:=true" test coverageReport \
            && sbt coverageAggregate
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
