name: CI

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: sbt tests/test cli/test
