name: CI

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v10
      - run: |
          if [[ -n "$COVERALLS_REPO_TOKEN" ]]; then
            sbt clean "set core/coverageEnabled:=true" "set cli/coverageEnabled:=true" test coverageReport \
              && sbt coverageAggregate coveralls;
          else
            sbt clean "set core/coverageEnabled:=true" "set cli/coverageEnabled:=true" test coverageReport;
          fi
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
