name: CI

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Tests Coverage
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: |
          sbt clean "set core/coverageEnabled:=true" "set cli/coverageEnabled:=true" test coverageReport \
            && sbt coverageAggregate
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
