name: PR

on:
  pull_request:

jobs:
  checks:
    name: Scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: sbt scalafmtCheckAll scalafmtSbtCheck
  self-checks-core:
    name: Self Blinky core module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: adopt:8
          apps: bloop
      - run: ./.github/scripts/setup.sh
      - run: sbt "runCurrent \"ci-tests/core.blinky.conf\" --multiRun 1/1"
  self-checks-cli:
    name: Self Blinky cli module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: adopt:8
          apps: bloop
      - run: ./.github/scripts/setup.sh
      - run: sbt "runCurrent \"ci-tests/cli.blinky.conf\" --multiRun 1/1"
  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: adopt:8
          apps: bloop
      - run: ./.github/scripts/setup.sh
      - run: sbt runExamples
  scalaTests:
    name: Run Tests Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scalaVersion: [2.12.10, 2.12.11, 2.12.13, 2.13.2, 2.13.3, 2.13.4, 2.13.5]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: sbt "++ $VERSION_TO_TEST!" core/test tests/test
        env:
          VERSION_TO_TEST: ${{ matrix.scalaVersion }}
