name: PR

on:
  pull_request:

jobs:
#  checks:
#    name: Scalafmt
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: coursier/setup-action@v1
#        with:
#          jvm: adopt:8
#      - run: sbt scalafmtCheckAll scalafmtSbtCheck
#  self-checks-core:
#    name: Self Blinky core module
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - uses: coursier/setup-action@v1
#        with:
#          jvm: adopt:8
#          apps: bloop
#      - run: ./.github/scripts/setup.sh
#      - run: sbt "runCurrent \"ci-tests/core.blinky.conf\" --multiRun 1/1"
#  self-checks-cli:
#    name: Self Blinky cli module
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - uses: coursier/setup-action@v1
#        with:
#          jvm: adopt:8
#          apps: bloop
#      - run: ./.github/scripts/setup.sh
#      - run: sbt "runCurrent \"ci-tests/cli.blinky.conf\" --multiRun 1/1"
#  integration:
#    name: Integration
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - uses: coursier/setup-action@v1
#        with:
#          jvm: adopt:8
#          apps: bloop
#      - run: ./.github/scripts/setup.sh
#      - run: sbt runExamples
  communityTests:
    name: Community projects tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/setup-action@v1
        with:
          jvm: adopt:8
      - run: |
          ./.github/scripts/setup.sh
          sbt "runCommunityProjects scalameta"
  mdoc-test:
    name: Run mdoc and check for warnings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sbt mdoc 2>&1 | tee output.txt
          if grep -q 'warning' output.txt; then
            echo "mdoc warnings found!"
            exit 1
          fi
