name: PR

on:
  pull_request:

jobs:
  checks:
    name: Scalafmt
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: sbt scalafmtCheckAll scalafmtSbtCheck
  self-checks-core:
    name: Self Blinky core
    #    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: adopt:8
          apps: bloop
      - run: ./.github/scripts/setup.sh
      - run: sbt "runCurrent \"ci-tests/core.blinky.conf\" --multiRun 1/1"
  self-checks-cli:
    name: Self Blinky core
    #    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: adopt:8
          apps: bloop
      - run: ./.github/scripts/setup.sh
      - run: sbt "runCurrent \"ci-tests/cli.blinky.conf\" --multiRun 1/1"
  integration:
    name: Integration
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: adopt:8
          apps: bloop
      - run: ./.github/scripts/setup.sh
      - run: sbt runExamples
