name: Release
on:
  push:
    branches: [master]
    tags: ["*"]
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: git fetch --unshallow
      - run: |
          sbt ci-release
          sbt docs/docusaurusPublishGhpages
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
